apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-postgresql-data
  namespace: {{ .Release.Namespace }}
  annotations:
    # Keeps the PVC (and data) when running `helm uninstall`
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresql.storage }}
