apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  DATABASE_URL: "postgresql://{{ .Values.postgresql.username }}:{{ .Values.postgresql.password }}@{{ .Release.Name }}-postgresql:5432/{{ .Values.postgresql.database }}"
  POSTGRES_PASSWORD: "{{ .Values.postgresql.password }}"
  AZURE_ACCOUNT_KEY: "{{ .Values.azure.accountKey }}"
  DJANGO_SECRET_KEY: "{{ .Values.django.secretKey }}"
